default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: phonebook_development
  username: indrajeet
  password: 

production:
  <<: *default
  database: phonebook_production
  username: indrajeet
  password: 